url: http://fin-ger.github.io/FreezingArcher/
baseurl: FreezingArcher

# Site settings
title: FreezingArcher
email: FreezingArcher@gmail.com
description: "FreezingArcher is a lightweight cross platform framework (currently only GNU/Linux x64 and Windows x64 are officially supported) for 3D game development in C# (mono/.NET)."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 36bbfe
  secondary: 03aafe
  secondary-dark: 333

# Team names, titles and social links
people:
- name: David Bögelsack
  pic: 1
  position: Lead Developer For Rendering Architecture
  social:
    - title: github
      url: https://github.com/DavidB3

- name: Fin Christensen
  pic: 2
  position: Core Developer
  social:
    - title: github
      url: https://github.com/fin-ger

- name: Willi Failla
  pic: 3
  position: Developer
  social:
    - title: github
      url: https://github.com/wfailla

- name: Martin Koppehel
  pic: 4
  position: Core Developer
  social:
    - title: github
      url: https://github.com/martin31821

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/fin-ger/FreezingArcher

# Build settings
markdown: kramdown
permalink: pretty
